theme: jekyll-theme-cayman
title: Murat Orhan Progress Journal
description: BDA 503 - Data Analytics Essentials - MEF University

Week 2
RMarkdown homework was uploaded.
[Link] (file:///C:/Users/Murat/Desktop/assignment_2.html)
